"""Pure-Python reimplementation of the thin slice of the cisTEM Database
class that is actually used from Python (see pycistem/database/__init__.py
and pycistem/pycore/PLAN.md).

The C++ Database class (cisTEM/src/core/database.cpp) has 350+ methods
covering the full GUI schema; only a handful are ever called from this
repo's Python code, so only those are ported here. Table DDL was captured
by dumping `.schema` from a project created by the compiled extension
(pycistem.core.Project.CreateNewProject) rather than transcribing each of
the C++ CreateXTable() methods by hand.
"""

import os
import sqlite3
from pathlib import Path

# Captured via `sqlite3 <db created by pycistem.core.Project.CreateNewProject> .schema`
SCHEMA_SQL = [
    "CREATE TABLE MASTER_SETTINGS(NUMBER INTEGER PRIMARY KEY, PROJECT_DIRECTORY TEXT, PROJECT_NAME TEXT, CURRENT_VERSION INTEGER, TOTAL_CPU_HOURS REAL, TOTAL_JOBS_RUN INTEGER, CISTEM_VERSION_TEXT TEXT, CURRENT_WORKFLOW INTEGER )",
    "CREATE TABLE PARTICLE_PICKING_LIST(PICKING_ID INTEGER PRIMARY KEY, DATETIME_OF_RUN INTEGER, PICKING_JOB_ID INTEGER, PARENT_IMAGE_ASSET_ID INTEGER, PICKING_ALGORITHM INTEGER, CHARACTERISTIC_RADIUS REAL, MAXIMUM_RADIUS REAL, THRESHOLD_PEAK_HEIGHT REAL, HIGHEST_RESOLUTION_USED_IN_PICKING REAL, MIN_DIST_FROM_EDGES INTEGER, AVOID_HIGH_VARIANCE INTEGER, AVOID_HIGH_LOW_MEAN INTEGER, NUM_BACKGROUND_BOXES INTEGER, MANUAL_EDIT INTEGER )",
    "CREATE TABLE RUNNING_JOBS(JOB_NUMBER INTEGER PRIMARY KEY, JOB_CODE TEXT, MANAGER_IP_ADDRESS INTEGER )",
    "CREATE TABLE RUN_PROFILES(RUN_PROFILE_ID INTEGER PRIMARY KEY, PROFILE_NAME TEXT, MANAGER_RUN_COMMAND TEXT, GUI_ADDRESS TEXT, CONTROLLER_ADDRESS TEXT, COMMANDS_ID INTEGER )",
    "CREATE TABLE MOVIE_ASSETS(MOVIE_ASSET_ID INTEGER PRIMARY KEY, NAME TEXT, FILENAME TEXT, POSITION_IN_STACK INTEGER, X_SIZE INTEGER, Y_SIZE INTEGER, NUMBER_OF_FRAMES INTEGER, VOLTAGE REAL, PIXEL_SIZE REAL, DOSE_PER_FRAME REAL, SPHERICAL_ABERRATION REAL, GAIN_FILENAME TEXT, DARK_FILENAME TEXT, OUTPUT_BINNING_FACTOR REAL, CORRECT_MAG_DISTORTION INTEGER, MAG_DISTORTION_ANGLE REAL, MAG_DISTORTION_MAJOR_SCALE REAL, MAG_DISTORTION_MINOR_SCALE REAL, PROTEIN_IS_WHITE INTEGER, EER_SUPER_RES_FACTOR INTEGER, EER_FRAMES_PER_IMAGE INTEGER )",
    "CREATE TABLE IMAGE_ASSETS(IMAGE_ASSET_ID INTEGER PRIMARY KEY, NAME TEXT, FILENAME TEXT, POSITION_IN_STACK INTEGER, PARENT_MOVIE_ID INTEGER, ALIGNMENT_ID INTEGER, CTF_ESTIMATION_ID INTEGER, X_SIZE INTEGER, Y_SIZE INTEGER, PIXEL_SIZE REAL, VOLTAGE REAL, SPHERICAL_ABERRATION REAL, PROTEIN_IS_WHITE INTEGER, ORIGINAL_X_SIZE INTEGER, ORIGINAL_Y_SIZE INTEGER, CROP_CENTER_X INTEGER, CROP_CENTER_Y INTEGER )",
    "CREATE TABLE MOVIE_GROUP_LIST(GROUP_ID INTEGER PRIMARY KEY, GROUP_NAME TEXT, LIST_ID INTEGER )",
    "CREATE TABLE MOVIE_ALIGNMENT_LIST(ALIGNMENT_ID INTEGER PRIMARY KEY, DATETIME_OF_RUN INTEGER, ALIGNMENT_JOB_ID INTEGER, MOVIE_ASSET_ID INTEGER, OUTPUT_FILE TEXT, VOLTAGE REAL, PIXEL_SIZE REAL, EXPOSURE_PER_FRAME REAL, PRE_EXPOSURE_AMOUNT REAL, MIN_SHIFT REAL, MAX_SHIFT REAL, SHOULD_DOSE_FILTER INTEGER, SHOULD_RESTORE_POWER INTEGER, TERMINATION_THRESHOLD REAL, MAX_ITERATIONS INTEGER, BFACTOR INTEGER, SHOULD_MASK_CENTRAL_CROSS INTEGER, HORIZONTAL_MASK INTEGER, VERTICAL_MASK INTEGER, SHOULD_INCLUDE_ALL_FRAMES_IN_SUM INTEGER, FIRST_FRAME_TO_SUM INTEGER, LAST_FRAME_TO_SUM INTEGER, ORIGINAL_X_SIZE INTEGER, ORIGINAL_Y_SIZE INTEGER, CROP_CENTER_X INTEGER, CROP_CENTER_Y INTEGER )",
    "CREATE TABLE IMAGE_GROUP_LIST(GROUP_ID INTEGER PRIMARY KEY, GROUP_NAME TEXT, LIST_ID INTEGER )",
    "CREATE TABLE PARTICLE_POSITION_ASSETS(PARTICLE_POSITION_ASSET_ID INTEGER PRIMARY KEY, PARENT_IMAGE_ASSET_ID INTEGER, PICKING_ID INTEGER, PICK_JOB_ID INTEGER, X_POSITION REAL, Y_POSITION REAL, PEAK_HEIGHT REAL, TEMPLATE_ASSET_ID INTEGER, TEMPLATE_PSI REAL, TEMPLATE_THETA REAL, TEMPLATE_PHI REAL )",
    "CREATE TABLE PARTICLE_POSITION_GROUP_LIST(GROUP_ID INTEGER PRIMARY KEY, GROUP_NAME TEXT, LIST_ID INTEGER )",
    "CREATE TABLE ESTIMATED_CTF_PARAMETERS(CTF_ESTIMATION_ID INTEGER PRIMARY KEY, CTF_ESTIMATION_JOB_ID INTEGER, DATETIME_OF_RUN INTEGER, IMAGE_ASSET_ID INTEGER, ESTIMATED_ON_MOVIE_FRAMES INTEGER, VOLTAGE REAL, SPHERICAL_ABERRATION REAL, PIXEL_SIZE REAL, AMPLITUDE_CONTRAST REAL, BOX_SIZE INTEGER, MIN_RESOLUTION REAL, MAX_RESOLUTION REAL, MIN_DEFOCUS REAL, MAX_DEFOCUS REAL, DEFOCUS_STEP REAL, RESTRAIN_ASTIGMATISM INTEGER, TOLERATED_ASTIGMATISM REAL, FIND_ADDITIONAL_PHASE_SHIFT INTEGER, MIN_PHASE_SHIFT REAL, MAX_PHASE_SHIFT REAL, PHASE_SHIFT_STEP REAL, DEFOCUS1 REAL, DEFOCUS2 REAL, DEFOCUS_ANGLE REAL, ADDITIONAL_PHASE_SHIFT REAL, SCORE REAL, DETECTED_RING_RESOLUTION REAL, DETECTED_ALIAS_RESOLUTION REAL, OUTPUT_DIAGNOSTIC_FILE TEXT, NUMBER_OF_FRAMES_AVERAGED INTEGER, LARGE_ASTIGMATISM_EXPECTED INTEGER, ICINESS REAL, TILT_ANGLE REAL, TILT_AXIS REAL, SAMPLE_THICKNESS REAL, SAMPLE_THICKNESS_JSON TEXT, DETERMINE_TILT INTEGER, FIT_NODES INTEGER, FIT_NODES_1D INTEGER, FIT_NODES_2D INTEGER, FIT_NODES_LOW_LIMIT REAL, FIT_NODES_HIGH_LIMIT REAL, FIT_NODES_ROUNDED_SQUARE INTEGER, FIT_NODES_DOWNWEIGHT_NODES INTEGER, RESAMPLE_IF_NESCESSARY INTEGER, TARGET_PIXEL_SIZE REAL )",
    "CREATE TABLE VOLUME_ASSETS(VOLUME_ASSET_ID INTEGER PRIMARY KEY, NAME TEXT, FILENAME TEXT, RECONSTRUCTION_JOB_ID INTEGER, PIXEL_SIZE REAL, X_SIZE INTEGER, Y_SIZE INTEGER, Z_SIZE INTEGER, HALF_MAP1_FILENAME TEXT, HALF_MAP2_FILENAME TEXT )",
    "CREATE TABLE VOLUME_GROUP_LIST(GROUP_ID INTEGER PRIMARY KEY, GROUP_NAME TEXT, LIST_ID INTEGER )",
    "CREATE TABLE ATOMIC_COORDINATES_ASSETS(ATOMIC_COORDINATES_ASSET_ID INTEGER PRIMARY KEY, NAME TEXT, FILENAME TEXT, SIMULATION_3D_JOB_ID INTEGER, X_SIZE INTEGER, Y_SIZE INTEGER, Z_SIZE INTEGER, PDB_ID TEXT, PDB_AVG_BFACTOR REAL, PDB_STD_BFACTOR REAL, EFFECTIVE_WEIGHT REAL )",
    "CREATE TABLE ATOMIC_COORDINATES_GROUP_LIST(GROUP_ID INTEGER PRIMARY KEY, GROUP_NAME TEXT, LIST_ID INTEGER )",
    "CREATE TABLE REFINEMENT_PACKAGE_ASSETS(REFINEMENT_PACKAGE_ASSET_ID INTEGER PRIMARY KEY, NAME TEXT, STACK_FILENAME TEXT, STACK_BOX_SIZE INTEGER, OUTPUT_PIXEL_SIZE REAL, SYMMETRY TEXT, MOLECULAR_WEIGHT REAL, PARTICLE_SIZE REAL, NUMBER_OF_CLASSES INTEGER, NUMBER_OF_REFINEMENTS INTEGER, LAST_REFINEMENT_ID INTEGER, STACK_HAS_WHITE_PROTEIN INTEGER )",
    "CREATE TABLE TEMPLATE_MATCHES_PACKAGE_ASSETS(TEMPLATE_MATCHES_PACKAGE_ASSET_ID INTEGER PRIMARY KEY, NAME TEXT, STARFILE_FILENAME TEXT, NUMBER_OF_MATCHES INTEGER, NUMER_OF_IMAGES INTEGER )",
    "CREATE TABLE REFINEMENT_LIST(REFINEMENT_ID INTEGER PRIMARY KEY, REFINEMENT_PACKAGE_ASSET_ID INTEGER, NAME TEXT, RESOLUTION_STATISTICS_ARE_GENERATED INTEGER, DATETIME_OF_RUN INTEGER, STARTING_REFINEMENT_ID INTEGER, NUMBER_OF_PARTICLES INTEGER, NUMBER_OF_CLASSES INTEGER, RESOLUTION_STATISTICS_BOX_SIZE INTEGER, RESOLUTION_STATISTICS_PIXEL_SIZE REAL, PERCENT_USED REAL )",
    "CREATE TABLE MOVIE_ASSETS_METADATA(MOVIE_ASSET_METADATA_ID INTEGER PRIMARY KEY, MOVIE_ASSET_ID INTEGER, METADATA_SOURCE TEXT, CONTENT_JSON TEXT, TILT_ANGLE REAL, STAGE_POSITION_X REAL, STAGE_POSITION_Y REAL, STAGE_POSITION_Z REAL, IMAGE_SHIFT_X REAL, IMAGE_SHIFT_Y REAL, EXPOSURE_DOSE REAL, ACQUISITION_TIME INTEGER )",
    "CREATE TABLE TEMPLATE_MATCH_LIST(TEMPLATE_MATCH_ID INTEGER PRIMARY KEY, JOB_NAME TEXT, DATETIME_OF_RUN INTEGER, TEMPLATE_MATCH_JOB_ID INTEGER, JOB_TYPE_CODE INTEGER, INPUT_TEMPLATE_MATCH_ID INTEGER, IMAGE_ASSET_ID INTEGER, REFERENCE_VOLUME_ASSET_ID INTEGER, IS_ACTIVE INTEGER, USED_SYMMETRY TEXT, USED_PIXEL_SIZE REAL, USED_VOLTAGE REAL, USED_SPHERICAL_ABERRATION REAL, USED_AMPLITUDE_CONTRAST REAL, USED_DEFOCUS1 REAL, USED_DEFOCUS2 REAL, USED_DEFOCUS_ANGLE REAL, USED_PHASE_SHIFT REAL, LOW_RESOLUTION_LIMIT REAL, HIGH_RESOLUTION_LIMIT REAL, OUT_OF_PLANE_ANGULAR_STEP REAL, IN_PLANE_ANGULAR_STEP REAL, DEFOCUS_SEARCH_RANGE REAL, DEFOCUS_STEP REAL, PIXEL_SIZE_SEARCH_RANGE REAL, PIXEL_SIZE_STEP REAL, REFINEMENT_THRESHOLD REAL, USED_THRESHOLD REAL, REF_BOX_SIZE_IN_ANGSTROMS REAL, MASK_RADIUS REAL, MIN_PEAK_RADIUS REAL, XY_CHANGE_THRESHOLD REAL, EXCLUDE_ABOVE_XY_THRESHOLD INTEGER, MIP_OUTPUT_FILE TEXT, SCALED_MIP_OUTPUT_FILE TEXT, AVG_OUTPUT_FILE TEXT, STD_OUTPUT_FILE TEXT, PSI_OUTPUT_FILE TEXT, THETA_OUTPUT_FILE TEXT, PHI_OUTPUT_FILE TEXT, DEFOCUS_OUTPUT_FILE TEXT, PIXEL_SIZE_OUTPUT_FILE TEXT, HISTOGRAM_OUTPUT_FILE TEXT, PROJECTION_RESULT_OUTPUT_FILE TEXT )",
    "CREATE TABLE CLASSIFICATION_LIST(CLASSIFICATION_ID INTEGER PRIMARY KEY, REFINEMENT_PACKAGE_ASSET_ID INTEGER, NAME TEXT, CLASS_AVERAGE_FILE TEXT, REFINEMENT_WAS_IMPORTED_OR_GENERATED INTEGER, DATETIME_OF_RUN INTEGER, STARTING_CLASSIFICATION_ID INTEGER, NUMBER_OF_PARTICLES INTEGER, NUMBER_OF_CLASSES INTEGER, LOW_RESOLUTION_LIMIT REAL, HIGH_RESOLUTION_LIMIT REAL, MASK_RADIUS REAL, ANGULAR_SEARCH_STEP REAL, SEARCH_RANGE_X REAL, SEARCH_RANGE_Y REAL, SMOOTHING_FACTOR REAL, EXCLUDE_BLANK_EDGES INTEGER, AUTO_PERCENT_USED INTEGER, PERCENT_USED REAL )",
    "CREATE TABLE CLASSIFICATION_SELECTION_LIST(SELECTION_ID INTEGER PRIMARY KEY, SELECTION_NAME TEXT, CREATION_DATE INTEGER, REFINEMENT_PACKAGE_ID INTEGER, CLASSIFICATION_ID INTEGER, NUMBER_OF_CLASSES INTEGER, NUMBER_OF_SELECTIONS INTEGER )",
    "CREATE TABLE STARTUP_LIST(STARTUP_ID INTEGER PRIMARY KEY, REFINEMENT_PACKAGE_ASSET_ID INTEGER, NAME TEXT, NUMBER_OF_STARTS INTEGER, NUMBER_OF_CYCLES INTEGER, INITIAL_RES_LIMIT REAL, FINAL_RES_LIMIT REAL, AUTO_MASK INTEGER, AUTO_PERCENT_USED INTEGER, INITIAL_PERCENT_USED REAL, FINAL_PERCENT_USED REAL, MASK_RADIUS REAL, APPLY_LIKELIHOOD_BLURRING INTEGER, SMOOTHING_FACTOR REAL )",
    "CREATE TABLE RECONSTRUCTION_LIST(RECONSTRUCTION_ID INTEGER PRIMARY KEY, REFINEMENT_PACKAGE_ID INTEGER, REFINEMENT_ID INTEGER, NAME TEXT, INNER_MASK_RADIUS REAL, OUTER_MASK_RADIUS REAL, RESOLUTION_LIMIT REAL, SCORE_WEIGHT_CONVERSION REAL, SHOULD_ADJUST_SCORES INTEGER, SHOULD_CROP_IMAGES INTEGER, SHOULD_SAVE_HALF_MAPS INTEGER, SHOULD_LIKELIHOOD_BLUR INTEGER, SMOOTHING_FACTOR REAL, CLASS_NUMBER INTEGER, VOLUME_ASSET_ID INTEGER )",
    "CREATE TABLE PROCESS_LOCK(NUMBER INTEGER PRIMARY KEY, ACTIVE_PROCESS INTEGER, ACTIVE_HOST TEXT )",
]

# cisTEM/src/core/defines.h: #define INTEGER_DATABASE_VERSION 2
INTEGER_DATABASE_VERSION = 2
CISTEM_VERSION_TEXT = "pycore"


class Database:
    def __init__(self):
        self.is_open = False
        self.database_file = None
        self.connection = None
        self._batch_table = None
        self._batch_columns = None
        self._batch_rows = None

    def CreateNewDatabase(self, wanted_database_file):
        if self.is_open:
            raise RuntimeError("Attempting to create a new database, but there is already an open project")
        path = Path(wanted_database_file)
        if path.exists():
            raise RuntimeError("Attempting to create a new database, but the file already exists")
        path = path.absolute()
        self.connection = sqlite3.connect(str(path), isolation_level=None)
        self.database_file = path
        self.is_open = True
        return True

    def Open(self, file_to_open, disable_locking=False):
        if self.is_open:
            raise RuntimeError("Attempting to open a database, but there is already an open project")
        path = Path(file_to_open)
        if not path.exists():
            raise RuntimeError("Attempting to open a new database, but the file does not exist")
        self.connection = sqlite3.connect(str(path), isolation_level=None)
        self.database_file = path
        self.is_open = True
        return True

    def CreateAllTables(self):
        for statement in SCHEMA_SQL:
            self.ExecuteSQL(statement)
        return True

    def DeleteTable(self, table_name):
        return self.ExecuteSQL(f"DROP TABLE IF EXISTS {table_name}")

    def ExecuteSQL(self, command):
        self.connection.execute(command)
        return True

    def ReturnSingleLongFromSelectCommand(self, select_command):
        cur = self.connection.execute(select_command)
        row = cur.fetchone()
        if row is None or row[0] is None:
            return 0
        return int(row[0])

    def GetMasterSettings(self):
        cur = self.connection.execute("SELECT * FROM MASTER_SETTINGS")
        row = cur.fetchone()
        if row is None:
            return None
        return {
            "project_directory": row[1],
            "project_name": row[2],
            "integer_database_version": row[3],
            "total_cpu_hours": row[4],
            "total_jobs_run": row[5],
            "cistem_version_text": row[6],
            "current_workflow": row[7],
        }

    def CreateProcessLockTable(self):
        self.ExecuteSQL(
            "CREATE TABLE PROCESS_LOCK(NUMBER INTEGER PRIMARY KEY, ACTIVE_PROCESS INTEGER, ACTIVE_HOST TEXT )"
        )

    def BeginMovieAssetInsert(self):
        self._batch_table = "MOVIE_ASSETS"
        self._batch_columns = [
            "MOVIE_ASSET_ID", "NAME", "FILENAME", "POSITION_IN_STACK", "X_SIZE", "Y_SIZE",
            "NUMBER_OF_FRAMES", "VOLTAGE", "PIXEL_SIZE", "DOSE_PER_FRAME", "SPHERICAL_ABERRATION",
            "GAIN_FILENAME", "DARK_FILENAME", "OUTPUT_BINNING_FACTOR", "CORRECT_MAG_DISTORTION",
            "MAG_DISTORTION_ANGLE", "MAG_DISTORTION_MAJOR_SCALE", "MAG_DISTORTION_MINOR_SCALE",
            "PROTEIN_IS_WHITE", "EER_SUPER_RES_FACTOR", "EER_FRAMES_PER_IMAGE",
        ]
        self._batch_rows = []

    def AddNextMovieAsset(
        self,
        movie_asset_id, name, filename, position_in_stack, x_size, y_size, number_of_frames,
        voltage, pixel_size, dose_per_frame, spherical_aberration, gain_filename, dark_filename,
        output_binning_factor, correct_mag_distortion, mag_distortion_angle,
        mag_distortion_major_scale, mag_distortion_minor_scale, protein_is_white,
        eer_super_res_factor, eer_frames_per_image,
    ):
        self._batch_rows.append((
            movie_asset_id, name, filename, position_in_stack, x_size, y_size, number_of_frames,
            voltage, pixel_size, dose_per_frame, spherical_aberration, gain_filename, dark_filename,
            output_binning_factor, correct_mag_distortion, mag_distortion_angle,
            mag_distortion_major_scale, mag_distortion_minor_scale, protein_is_white,
            eer_super_res_factor, eer_frames_per_image,
        ))

    def EndMovieAssetInsert(self):
        placeholders = ",".join("?" * len(self._batch_columns))
        columns = ",".join(self._batch_columns)
        sql = f"INSERT OR REPLACE INTO {self._batch_table} ({columns}) VALUES ({placeholders})"
        self.connection.executemany(sql, self._batch_rows)
        self._batch_table = None
        self._batch_columns = None
        self._batch_rows = None

    def CheckandUpdateSchema(self):
        # Schema migration across historical cisTEM database versions is
        # out of scope for pycore: CreateAllTables() always creates the
        # latest schema, so a database created by pycore never needs
        # migrating. Kept as a no-op for API compatibility.
        return True

    def Close(self, remove_lock=True):
        if not self.is_open:
            return
        if remove_lock:
            my_process_id = os.getpid()
            database_process_id = self.ReturnSingleLongFromSelectCommand(
                "SELECT ACTIVE_PROCESS FROM PROCESS_LOCK"
            )
            if my_process_id != database_process_id and my_process_id != 0 and database_process_id > 0:
                pass  # lock held by another process, leave it in place
            else:
                self.DeleteTable("PROCESS_LOCK")
                self.CreateProcessLockTable()

        self.connection.commit()
        self.connection.close()
        self.connection = None
        self.is_open = False
