from dataclasses import dataclass

@dataclass
class RefineTemplateParameters:
    input_search_image: str,
    input_reconstruction: str,
    pixel_size: float = 1.0,
    amplitude_contrast: float = 0.07,
    defocus1: float = 20000,
    defocus2: float = 20000,
    defocus_angle: float = 0.0,
    low_resolution_limit: float,
    high_resolution_limit: float,
    angular_range: float,
    angular_step: float,
    best_parameters_to_keep: int,
    defocus_search_range: float,
    defocus_search_step: float,
    defocus_refine_step: float,
    pixel_size_search_range: float,
    pixel_size_step: float,
    pixel_size_refine_step: float,
    padding: float,
    ctf_refinement: bool,
    mask_radius: float,
    phase_shift: float,
    mip_input_filename: str,
    scaled_mip_input_filename: str,
    best_psi_input_filename: str,
    best_theta_input_filename: str,
    best_phi_input_filename: str,
    best_defocus_input_filename: str,
    best_pixel_size_input_filename: str,
    best_psi_output_file: str,
    best_theta_output_file: str,
    best_phi_output_file: str,
    best_defocus_output_file: str,
    best_pixel_size_output_file: str,
    mip_output_file: str,
    scaled_mip_output_file: str,
    wanted_threshold: float,
    min_peak_radius: float,
    xy_change_threshold: float,
    exclude_above_xy_threshold: bool,
    my_symmetry: str,
    in_plane_angular_step: float,
    first_search_position: int,
    last_search_position: int,
    image_number_for_gui: int,
    number_of_jobs_per_image_in_gui: int,
    result_number: int,
    max_threads: int,
    directory_for_results: str,
    threshold_for_result_plotting: float,
    filename_for_gui_result_image: str

