name: pycistem CI

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python: ['3.9','3.10','3.11']

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install Hatch
      run: pip install hatch
    - name: Build project
      run: hatch build
    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: 'Wheel for Python ${{ matrix.python }}'
        path: dist/*.whl

    - name: Publish
      if: contains(github.ref, 'tags')
      env:
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
        HATCH_INDEX_USER: __token__
      run: |
        hatch publish dist/*.whl
